"""Updated models for bidding system

Revision ID: 4018c75d15e0
Revises: 
Create Date: 2025-02-03 18:17:31.277442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4018c75d15e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_image')
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.drop_column('sale_status')

    op.create_table('auction_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('auction_item_id', sa.INTEGER(), nullable=False),
    sa.Column('image_filename', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['auction_item_id'], ['auction_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
